SELECT TOP (1000) [ORDERNUMBER]
      ,[QUANTITYORDERED]
      ,[PRICEEACH]
      ,[ORDERLINENUMBER]
      ,[SALES]
      ,[ORDERDATE]
      ,[QTR_ID]
      ,[MONTH_ID]
      ,[YEAR_ID]
      ,[MSRP]
      ,[PRODUCTCODE]
      ,[PHONE]
      ,[ADDRESSLINE1]
      ,[ADDRESSLINE2]
      ,[TERRITORY]
      ,[CONTACTLASTNAME]
      ,[CONTACTFIRSTNAME]
      ,[Status_ID]
      ,[Product_ID]
      ,[Customer_ID]
      ,[City_ID]
      ,[State_ID]
      ,[Postal_ID]
      ,[Country_ID]
      ,[DealSize_ID]
  FROM [Connection_database].[dbo].[FACT]
